### ISSUE TITLE
Discovery issue since inception panel timeout

### ISSUE THREAD

**Issue by jasonpstokes** [matthew-larner/inception-mqtt#11]
Thanks for this project Matthew, it's been working great for months!

After updating HA to 2023.8.3 though, noticed the Inception Panel was not responding to inspection-mqtt with timeouts reported in the logs. A restart of the inception panel fixed this, but the devices in HA are still offline. Seems unlikely related, but any ideas or anything you can point me to, please? 

The `inception` topic_prefix updates when opening doors etc as expected, so inception-mqtt container is working:
![image](https://github.com/matthew-larner/inception-mqtt/assets/29766924/f1cde689-64cb-43b8-b126-41d7b9f66553)

But the only devices working in Home Assistant now are the three listed under the `homeassistant` topic_prefix - why only three? Or why isn't HA's autodiscovery reading the inception topic_prefix?

i.e. only warehouse still works, not office:
![image](https://github.com/matthew-larner/inception-mqtt/assets/29766924/d6d9583c-d437-4abc-99ac-18ee93ffcdb0)

And neither of these work in HA now:
![image](https://github.com/matthew-larner/inception-mqtt/assets/29766924/7152b1e4-2d02-4a3c-b530-db6a352a58a7)

![image](https://github.com/matthew-larner/inception-mqtt/assets/29766924/c5c1ca4b-f591-4739-921a-182d5e5ca530)

Is it possibly related to the [MQTT Name changes in 2023.8](https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099) affecting discovery? Except I was running 2023.8.1 or .2 before the latest update. 🤷‍♂️

inception-mqtt `configuration.yml`
```
# MQTT Settings
mqtt:
  broker: mqtt
  port: 1883
  username: **
  password: **
  qos: 2
  retain: true
  discovery: true
  discovery_prefix: homeassistant
  topic_prefix: inception
  availability_topic: inception/available

# Inception area config
inception:
  - base_url: http://10.0.1.**/api/v1
    port: 80
    username: **
    password: **
    polling_timeout: 60
    polling_delay: 60
```

PS Sorry it's taken an issue to say thanks. :)
